#ifndef ASS1_CLIENTSTATES_H
#define ASS1_CLIENTSTATES_H

#define CLIENTSTATE_INIT        0
#define CLIENTSTATE_AUTHWAIT    1
#define CLIENTSTATE_CMDWAIT     2
#define CLIENTSTATE_CMDPROCESS  3

#define ERRSTATE_CONNECTIONCLOSED 1
#define ERRSTATE_AUTHTIMEOUT 4
#define ERRSTATE_USERTIMEOUT 5
#define ERRSTATE_USERBLOCKED 2
#define ERRSTATE_QUITNOW 3

#endif //ASS1_CLIENTSTATES_H
